package com.hnmoma.driftbottle.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOTTLE_MSG_ATTACH.
 */
public class BottleMsgAttach {

    private Long id;
    /** Not-null value. */
    private String msgId;
    private String fileName;
    private String localUrl;
    private String remoteUrl;
    private Integer lengh;
    private String thumbUrl;
    private String message;
    private Long fileSize;
    private Boolean downloaded;
    private java.util.Date updateTime;

    public BottleMsgAttach() {
    }

    public BottleMsgAttach(Long id) {
        this.id = id;
    }

    public BottleMsgAttach(Long id, String msgId, String fileName, String localUrl, String remoteUrl, Integer lengh, String thumbUrl, String message, Long fileSize, Boolean downloaded, java.util.Date updateTime) {
        this.id = id;
        this.msgId = msgId;
        this.fileName = fileName;
        this.localUrl = localUrl;
        this.remoteUrl = remoteUrl;
        this.lengh = lengh;
        this.thumbUrl = thumbUrl;
        this.message = message;
        this.fileSize = fileSize;
        this.downloaded = downloaded;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMsgId() {
        return msgId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getLocalUrl() {
        return localUrl;
    }

    public void setLocalUrl(String localUrl) {
        this.localUrl = localUrl;
    }

    public String getRemoteUrl() {
        return remoteUrl;
    }

    public void setRemoteUrl(String remoteUrl) {
        this.remoteUrl = remoteUrl;
    }

    public Integer getLengh() {
        return lengh;
    }

    public void setLengh(Integer lengh) {
        this.lengh = lengh;
    }

    public String getThumbUrl() {
        return thumbUrl;
    }

    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Boolean getDownloaded() {
        return downloaded;
    }

    public void setDownloaded(Boolean downloaded) {
        this.downloaded = downloaded;
    }

    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

}
