package com.hnmoma.driftbottle.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hnmoma.driftbottle.model.Bottle;
import com.hnmoma.driftbottle.model.Chat;
import com.hnmoma.driftbottle.model.Attachment;
import com.hnmoma.driftbottle.model.User;
import com.hnmoma.driftbottle.model.BottleMsgAttach;
import com.hnmoma.driftbottle.model.Stranger;
import com.hnmoma.driftbottle.model.SensitiveWord;

import com.hnmoma.driftbottle.model.BottleDao;
import com.hnmoma.driftbottle.model.ChatDao;
import com.hnmoma.driftbottle.model.AttachmentDao;
import com.hnmoma.driftbottle.model.UserDao;
import com.hnmoma.driftbottle.model.BottleMsgAttachDao;
import com.hnmoma.driftbottle.model.StrangerDao;
import com.hnmoma.driftbottle.model.SensitiveWordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bottleDaoConfig;
    private final DaoConfig chatDaoConfig;
    private final DaoConfig attachmentDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig bottleMsgAttachDaoConfig;
    private final DaoConfig strangerDaoConfig;
    private final DaoConfig sensitiveWordDaoConfig;

    private final BottleDao bottleDao;
    private final ChatDao chatDao;
    private final AttachmentDao attachmentDao;
    private final UserDao userDao;
    private final BottleMsgAttachDao bottleMsgAttachDao;
    private final StrangerDao strangerDao;
    private final SensitiveWordDao sensitiveWordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bottleDaoConfig = daoConfigMap.get(BottleDao.class).clone();
        bottleDaoConfig.initIdentityScope(type);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        attachmentDaoConfig = daoConfigMap.get(AttachmentDao.class).clone();
        attachmentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bottleMsgAttachDaoConfig = daoConfigMap.get(BottleMsgAttachDao.class).clone();
        bottleMsgAttachDaoConfig.initIdentityScope(type);

        strangerDaoConfig = daoConfigMap.get(StrangerDao.class).clone();
        strangerDaoConfig.initIdentityScope(type);

        sensitiveWordDaoConfig = daoConfigMap.get(SensitiveWordDao.class).clone();
        sensitiveWordDaoConfig.initIdentityScope(type);

        bottleDao = new BottleDao(bottleDaoConfig, this);
        chatDao = new ChatDao(chatDaoConfig, this);
        attachmentDao = new AttachmentDao(attachmentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        bottleMsgAttachDao = new BottleMsgAttachDao(bottleMsgAttachDaoConfig, this);
        strangerDao = new StrangerDao(strangerDaoConfig, this);
        sensitiveWordDao = new SensitiveWordDao(sensitiveWordDaoConfig, this);

        registerDao(Bottle.class, bottleDao);
        registerDao(Chat.class, chatDao);
        registerDao(Attachment.class, attachmentDao);
        registerDao(User.class, userDao);
        registerDao(BottleMsgAttach.class, bottleMsgAttachDao);
        registerDao(Stranger.class, strangerDao);
        registerDao(SensitiveWord.class, sensitiveWordDao);
    }
    
    public void clear() {
        bottleDaoConfig.getIdentityScope().clear();
        chatDaoConfig.getIdentityScope().clear();
        attachmentDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        bottleMsgAttachDaoConfig.getIdentityScope().clear();
        strangerDaoConfig.getIdentityScope().clear();
        sensitiveWordDaoConfig.getIdentityScope().clear();
    }

    public BottleDao getBottleDao() {
        return bottleDao;
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

    public AttachmentDao getAttachmentDao() {
        return attachmentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BottleMsgAttachDao getBottleMsgAttachDao() {
        return bottleMsgAttachDao;
    }

    public StrangerDao getStrangerDao() {
        return strangerDao;
    }

    public SensitiveWordDao getSensitiveWordDao() {
        return sensitiveWordDao;
    }

}
