package com.hnmoma.driftbottle.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SENSITIVE_WORD.
 */
public class SensitiveWord implements java.io.Serializable {

    private String id;
    private String keyword;
    private String version;

    public SensitiveWord() {
    }

    public SensitiveWord(String id) {
        this.id = id;
    }

    public SensitiveWord(String id, String keyword, String version) {
        this.id = id;
        this.keyword = keyword;
        this.version = version;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

}
