package com.hnmoma.driftbottle.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User implements java.io.Serializable {

    private String userId;
    private String province;
    private String city;
    private String nickName;
    private String identityType;
    private String descript;
    private String headImg;
    private Integer age;
    private String job;
    private String hobby;
    private String constell;
    private String birthday;
    private Integer isVIP;
    private String tempHeadImg;

    public User() {
    }

    public User(String userId) {
        this.userId = userId;
    }

    public User(String userId, String province, String city, String nickName, String identityType, String descript, String headImg, Integer age, String job, String hobby, String constell, String birthday, Integer isVIP, String tempHeadImg) {
        this.userId = userId;
        this.province = province;
        this.city = city;
        this.nickName = nickName;
        this.identityType = identityType;
        this.descript = descript;
        this.headImg = headImg;
        this.age = age;
        this.job = job;
        this.hobby = hobby;
        this.constell = constell;
        this.birthday = birthday;
        this.isVIP = isVIP;
        this.tempHeadImg = tempHeadImg;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getIdentityType() {
        return identityType;
    }

    public void setIdentityType(String identityType) {
        this.identityType = identityType;
    }

    public String getDescript() {
        return descript;
    }

    public void setDescript(String descript) {
        this.descript = descript;
    }

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getHobby() {
        return hobby;
    }

    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    public String getConstell() {
        return constell;
    }

    public void setConstell(String constell) {
        this.constell = constell;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public Integer getIsVIP() {
        return isVIP;
    }

    public void setIsVIP(Integer isVIP) {
        this.isVIP = isVIP;
    }

    public String getTempHeadImg() {
        return tempHeadImg;
    }

    public void setTempHeadImg(String tempHeadImg) {
        this.tempHeadImg = tempHeadImg;
    }

}
